# Generated by Django 3.0.2 on 2020-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfcapp', '0002_auto_20200612_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='story',
            field=models.TextField(max_length=500),
        ),
    ]
