# Generated by Django 3.0.2 on 2020-08-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfcapp', '0007_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_link',
            field=models.CharField(max_length=255),
        ),
    ]
