# Generated by Django 3.0.2 on 2020-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfcapp', '0008_auto_20200809_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
